---
Name: idsk-blog-config
Only:
  moduleexists: silverstripe/blog
---
SilverStripe\Blog\Model\BlogController:
  disable_profiles: true
---
Name: idsk-userforms-config
Only:
  moduleexists: silverstripe/userforms
---
SilverStripe\UserForms\Model\UserDefinedForm:
  controller_name: Rasstislav\IdSk\Control\UserDefinedFormController
  block_default_userforms_css: true
  block_default_userforms_js: true
  enable_are_you_sure: false
---
Name: idsk-fluent-config
Only:
  moduleexists: tractorcow/silverstripe-fluent
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CMS\Search\SearchForm:
    class: TractorCow\Fluent\Search\FluentSearchForm
