---
Name: idsk-config
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
    class: Rasstislav\IdSk\TinyMCEConfig
---
Name: idsk-blog-config
Only:
  moduleexists: silverstripe/blog
---
SilverStripe\Blog\Model\BlogController:
  disable_profiles: true
---
Name: idsk-userforms-config
Only:
  moduleexists: silverstripe/userforms
---
SilverStripe\UserForms\Model\UserDefinedForm:
  controller_name: Rasstislav\IdSk\Control\UserDefinedFormController
  block_default_userforms_css: true
  block_default_userforms_js: true
  enable_are_you_sure: false
---
Name: idsk-nocaptcha-config
Only:
  moduleexists: undefinedoffset/silverstripe-nocaptcha
---
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector
SilverStripe\Core\Injector\Injector:
  UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
    properties:
      SiteKey: '`SS_NOCAPTCHA_SITE_KEY`'
      SecretKey: '`SS_NOCAPTCHA_SECRET_KEY`'
